alpha: 1e-5
shapes:
  z_dim: 256
  w_dim: 256
  in_channels: 256
  batch_size: 16
optimizers:
  generator_optimizer: 
    name: AdamW
    lr: 1e-5
  discriminator_optimizer: 
    name: AdamW
    lr: 1e-5
paths:
  anime_dataset_path: './Images'
  yml_path: Config.yml
  generated_images_path: ./Generated_images
  disc_weights_path: Loop/Disc_model_weights
  gen_weights_path: Loop/Gen_model_weights
device: 'cuda'
factors: [1, 1, 1, 1, 0.5, 0.25, 0.125, 0.0625, 0.03125]
steps: 6
epochs: 10 
weights_count: 3