# device='cuda'
# DATASET                 = "Women clothes"
# START_TRAIN_AT_IMG_SIZE = 8 #The authors start from 8x8 images instead of 4x4
# LEARNING_RATE           = 1e-3
# BATCH_SIZES             = [256, 128, 64, 32, 16, 8]
# CHANNELS_IMG            = 3

# LAMBDA_GP               = 10
# PROGRESSIVE_EPOCHS      = [30] * len(BATCH_SIZES)

shapes:
  z_dim: 256
  w_dim: 256
  in_channels: 256
device: 'cuda'
factors: [1, 1, 1, 1, 0.5, 0.25, 0.125, 0.0625, 0.03125]
steps: 30
aplpha: 1.0



